# This is a basic workflow to help you get started with Actions

name: Transport Actuator

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

  # Triggers the workflow every day
  schedule:
    - cron: "15 20 * * wed" # every day at (UTC) 08:15 and 20:15

  # Triggers the workflow on push events but only for the "master" branch
  pull_request_review:
    branches: ["master"]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "transport"
  transport:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Install python package
        run: pip3 install dockloader

      - name: List version
        run: |
          python3 --version
          pip3 --version
          pip3 list

      - name: "Login to GitHub Container Registry"
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}

      - uses: actions/checkout@v4
        with:
          ref: "master"

      - name: Transport image via dockloader
        run: dockloader transport --stdout --debug --namespace $(cat namespace) --repo  $(cat repository) --config-file tags

      - name: List all images
        run: docker image ls

      - name: Show current datetime
        run: date
